### ISSUE TITLE
Problem with Configerbot 

### ISSUE THREAD

**Issue by GostOfSarina** [hrostami/sb-server-configer#10]
طبق آموزش Readme 
دو دستور زیر را وارد کردم
Request:
/add_server X.XXX.XX.XX:22:root:secretpassword

Response bot:
Added server X.XXX.XX.XX

Request:
/token X.XXX.XX.XX token_bot

Response bot:
Added Token to server X.XXX.XX.XX

**Comment by GhostOfSarina** [comment]
After one day it replies to me Thanks.
