### ISSUE TITLE
NameError: name 'sing_box' is not defined

### ISSUE THREAD

**Issue by alighaffari3000** [hrostami/sb-server-configer#2]
بعد از اینکه تمام مشخصات را میگیره در انتها این ارور را میده:
Traceback (most recent call last):
  File "first.py", line 44, in <module>
    if sing_box:
NameError: name 'sing_box' is not defined

**Comment by hrostami** [comment]
درست شد، نسخه جدید رو بگیرید. اول کلینر رو ران کن بعد بقیه پروسه رو برو.
