### ISSUE TITLE
SNI changing from bot

### ISSUE THREAD

**Issue by zero0sight** [hrostami/sb-server-configer#4]
cant change sni from bot.
which one is correct?
/replace sni www.yahoo.com
/replace sni yahoo.com
/replace yahoo.com
...
none of them worked for me!

**Comment by hrostami** [comment]
send it like this: 
/replace uupload.ir
the one you sent doesn't work because it's been blocked in Iran, use something else!

**Comment by zero0sight** [comment]
برای من باگ خورد وقتی replace sni/ نوشتم. فک کردم مرحله بعد sni رو میگیره. حالا اومدم با یه سایت دیگه عوض کنم ولی بازم مقدار رو sni برمی گردوند. شاید خود sni کیورد چیزی هست که با تایپش باگ خورد. از اول کلیر کنی بزنی اوکیه
